// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	product "coretrix/internal/product"

	mock "github.com/stretchr/testify/mock"
)

// ProductRepository is an autogenerated mock type for the Repository type
type ProductRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ID
func (_m *ProductRepository) FindByID(ID int) (product.Product, error) {
	ret := _m.Called(ID)

	var r0 product.Product
	if rf, ok := ret.Get(0).(func(int) product.Product); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(product.Product)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(ID)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields:
func (_m *ProductRepository) GetAll() ([]product.Product, error) {
	ret := _m.Called()

	var r0 []product.Product
	if rf, ok := ret.Get(0).(func() []product.Product); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]product.Product)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
